export interface ImgurFile {
  id: string;
  title: string | null;
  description: string | null;
  datetime: number;
  type: string;
  animated: boolean;
  width: number;
  height: number;
  size: number;
  views: number;
  bandwidth: number;
  vote: number | null;
  favorite: boolean;
  nsfw: string | null;
  section: string | null;
  account_url: string | null;
  account_id: number;
  is_ad: boolean;
  in_most_viral: boolean;
  has_sound: boolean;
  tags: string[];
  ad_type: number;
  ad_url: string | null;
  edited: string;
  in_gallery: boolean;
  deletehash: string;
  name: string;
  link: string;
}
